version: "3"

networks:
  surveyapp-network:
    external: true

services:
  municipalsurvey:
    image: municipalsurvey:latest
    restart: unless-stopped
    ports: 
        - 8080:8080
    networks:
      - surveyapp-network
    volumes:
      - mysql-volume:/var/lib
    tty: true

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: Java_test.
    networks: 
      - surveyapp-network
    volumes: 
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: