version: "3.7"


networks: 
    default:
        external: 
            name: surveyapp-network
    
services: 
    municipalsurvey:
        image: openjdk:8-jdk-alpine
        ports: 
            - 8080:8080
        networks: 
            - default
        tty: true
        
volumes: 
    mysql-volume: